<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Resource Include="Assets/KA3005P.ico" />
    <ProjectReference Include="../Ka3005P.Core/Ka3005P.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="../../LICENSE" Link="LICENSE" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="../../THIRD-PARTY-NOTICES.md" Link="THIRD-PARTY-NOTICES.md" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="../../assets/reference/KoradS150.png" Link="ReferenceAssets/KoradS150.png" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="../../assets/reference/KoradD150.png" Link="ReferenceAssets/KoradD150.png" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="../../assets/reference/KoradM150.png" Link="ReferenceAssets/KoradM150.png" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets/KA3005P.ico</ApplicationIcon>
	<Version>0.1.1</Version>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <DebugType>embedded</DebugType>
  </PropertyGroup>
</Project>
